name: Android Lint Report

on: push

jobs:
  android-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17 and Android SDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Decode Google Service JSON
        env:
          ENCODED_STRING: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $ENCODED_STRING | base64 -d > app/google-services.json

      - name: Run lint
        run: ./gradlew lint
        continue-on-error: true

      - name: Lint Report
        uses: hidakatsuya/action-report-android-lint@v1.2.0
        with:
          result-path: 'app/build/reports/lint-results-debug.xml'
          fail-on-warning: false