name: Release

on:
  push:
    branches:
      - master
    paths:
      - 'buildSrc/src/main/java/com/vuxur/khayyam/ConfigurationData.kt'
  workflow_dispatch:
    inputs:
      name:
        description: "Release-Build"
        default: "Generate release build"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Version from Gradle File
        id: extract_version
        run: |
          VERSION_NAME=$(grep -Eo 'versionName = "(.+?)"' buildSrc/src/main/java/com/vuxur/khayyam/ConfigurationData.kt | cut -d '"' -f2)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Check if Tag Exists
        id: check_tag_exists
        uses: mukunku/tag-exists-action@v1.6.0
        with:
          tag: v${{ env.VERSION_NAME }}


      - name: Setup JDK 21 and Android SDK
        if: steps.check_tag_exists.outputs.exists == 'false'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - if: steps.check_tag_exists.outputs.exists == 'false'
        name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode Keystore
        if: steps.check_tag_exists.outputs.exists == 'false'
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_BASE_64 }}
        run: |
          echo $ENCODED_STRING | base64 -di > keystore.jks

      - name: Decode Google Service JSON
        if: steps.check_tag_exists.outputs.exists == 'false'
        env:
          ENCODED_STRING: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $ENCODED_STRING | base64 -di > app/google-services.json

      - name: Build Release APK
        if: steps.check_tag_exists.outputs.exists == 'false'
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: ./gradlew assembleRelease --stacktrace

      - name: Build Release Bundle
        if: steps.check_tag_exists.outputs.exists == 'false'
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: ./gradlew bundleRelease --stacktrace

      - name: Upload Release Build to Artifacts
        if: steps.check_tag_exists.outputs.exists == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: |
            app/build/outputs/apk/release/
            app/build/outputs/bundle/release/

      - name: Create GitHub Release
        if: steps.check_tag_exists.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION_NAME }}
          generate_release_notes: true
          prerelease: true
          files: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/bundle/release/app-release.aab
