name: Unit Test
on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17 and Android SDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          # Paths to cache, including Gradle caches and wrapper
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          # Key used to identify the cache. This should change if dependencies change
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          # Fallback keys used to restore the cache if the exact key isn't found
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Decode Google Service JSON
        env:
          ENCODED_STRING: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $ENCODED_STRING | base64 -d > app/google-services.json

      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/app/build/test-results/testDebugUnitTest/TEST-*.xml'
          summary: true
